#!/bin/bash
# Author: Talha Khan <talha@averred.net>, 13/07/2020

# Add Social WiFi files to site hotspot

# Check if we are running as root, if not rerun script as root
[ `whoami` = root ] || exec su -c $0 root

# Usage helper function
display_usage() {
        echo "This script must be run with super-user privileges."
        echo -e "Usage: $0 <UniFi Site ID>\n"
}

# Display usage and exit if no parameters supplied
if [ -z $1 ]
then
        display_usage
        exit 1
fi

# Display usage and exit if help requested
if [[ ( $1 == "-h" ) || ( $1 == "--help" ) ]]
then
        display_usage
        exit 0
fi

# Set $SITEID to first parameter
SITEID=${1,,}

# Check if UniFi Site ID supplied is invalid and exit
site_check = $(mongo --quiet --port 27117 ace --eval "db.getCollection('site').find({\"name\": \"$SITEID\"}).count()")
if [site_check -eq 0]
then
        display_usage
        echo "Invalid UniFi Site ID: $SITEID"
        echo "Please check the Site ID and try again."
        exit 1
fi

mkdir -p /usr/lib/unifi/data/sites/$SITEID/

# Create temporary folder and cd
TMPDIR=$(mktemp -d -t sw.$SITEID.XXXXXXXX)
cd $TMPDIR

# Download and unzip latest Social WiFi files
wget https://socialwifi.com/installation/ubiquity-unifi
unzip ubiquity-unifi

# Copy files to UniFi hotspot folder
if [ ! -d $TMPDIR/ubiquity_unifi ]
then
        display_usage
        echo "Error downloading/unzipping, please check URL"
        rm -rf $TMPDIR
        exit 1
fi

cp -R ubiquity_unifi/* /usr/lib/unifi/data/sites/$SITEID/

# Set correct file permissions
cd /usr/lib/unifi/data/sites/$SITEID/
chmod 640 config.properties app-unifi-hotspot-portal/index.html app-unifi-hotspot-portal/auth.html
chown unifi:unifi config.properties app-unifi-hotspot-portal/index.html app-unifi-hotspot-portal/auth.html

# Delete downloaded files
rm -rf $TMPDIR
